In [31]:
import pandas as pd
import numpy as np

In [32]:
df_train = pd.read_csv('/home/ankur/Desktop/dl_1000/1000_ml_projects/data/jigsaw-kaggle/jigsaw-agile-community-rules/train.csv')
df_test = pd.read_csv('/home/ankur/Desktop/dl_1000/1000_ml_projects/data/jigsaw-kaggle/jigsaw-agile-community-rules/test.csv')
df_sample_submission = pd.read_csv('/home/ankur/Desktop/dl_1000/1000_ml_projects/data/jigsaw-kaggle/jigsaw-agile-community-rules/sample_submission.csv')

In [33]:
pd.set_option('display.max_colwidth', None)

In [34]:
df_train.head(5)

,row_id,body,rule,subreddit,positive_example_1,positive_example_2,negative_example_1,negative_example_2,rule_violation
0,0,Banks don't want you to know this! Click here to know more!,"No Advertising: Spam, referral links, unsolicited advertising, and promotional content are not allowed.",Futurology,"If you could tell your younger self something different about sex, what would that be?\n\ni AM IN A CONTEST TO WIN FUNDING FOR MY SEX POSITIVE FILM: VOTE HERE:\n\nhttp://sheknows.offerpop.com/campaign/813112/entry/v144417",hunt for lady for jack off in neighbourhood http://url.inmusi.com/gakq,Watch Golden Globe Awards 2017 Live Online in HD Coverage without ADS (VIP STREAMS)\n=\n\nHD STREAM QUALITY >>> [WATCH LINK1](http://forum.submitexpress.com/viewtopic.php?f=9&t=215858)\n=\n\nHD BROADCASTING QUALITY >>> [WATCH LINK1](http://forum.submitexpress.com/viewtopic.php?f=9&t=215858)\n=\n\nMobile Compatibility: YES\n=\n\nNO ADS | NO ADS | ADS\n=\n,"DOUBLE CEE x BANDS EPPS - ""BIRDS""\n\nDOWNLOAD/STREAM:\n\nhttp://music.theblacksmithed.com/download/birds/",0
1,1,SD Stream [ ENG Link 1] (http://www.sportsstreams247.com/astra-giurgiu-vs-fc-austria-wien/),"No Advertising: Spam, referral links, unsolicited advertising, and promotional content are not allowed.",soccerstreams,[I wanna kiss you all over! Stunning!](http://www.oilflush.life/2017/01/26/6/),"LOLGA.COM is One of the First Professional Online Gold sites. By Now, As A Game Gold Seller, we've over more than 5 yrs Of Experience And Can Pass That On To Our Customers.","#Rapper \n🚨Straight Outta Cross Keys SC 🚨YouTube Search Beanie 864 Click Link BELOW To Hear Hit Single\n ""Ah Man"" \n Beanie 864 FEAT King Kota \n (King Kota Is Only 15!) Lit 🌡🔥👍💵💯Fr Fr \nhttps://youtu.be/tLqbV1Jmt5Y","[15 Amazing Hidden Features Of Google Search You Probably Don’t Know](http://www.madpeoples.com/2017/01/02 No one would argue the fact that Google is one of the most useful sihttp://www.madpeoples.com/2016/12/31/15-amazing-hidden-features-of-google-search-you-probably-dont-know/tes on the Internet. Unfortunately, most people only use about...?utm_source=reddit&utm_campaign=samreen&utm_medium=cpc)",0
2,2,Lol. Try appealing the ban and say you won't do it again.,No legal advice: Do not offer or request legal advice.,pcmasterrace,"Don't break up with him or call the cops. If you are willing to get beat up by him to stay with him, he is obviously a real winner and you know it, so you shouldn't leave him.",It'll be dismissed: https://en.wikipedia.org/wiki/New_York_Times_Co._v._Sullivan\n\nThe first amendment law here is SUPER settled.,Where is there a site that still works where you can jump the GPS. Is there a FAQ to do this with iPhone or Mac?,"Because this statement of his is true. It isn't freedom of the press, it's libel. And because of this, your post serves as a promotion for Trump. Reported.",1
3,3,she will come your home open her legs with and you http://sh.ors.it/PALI2,"No Advertising: Spam, referral links, unsolicited advertising, and promotional content are not allowed.",sex,Selling Tyrande codes for 3€ to paypal. PM. \nhttp://imgur.com/a/IMARW,tight pussy watch for your cock get her at this point http://macanasmagazine.com/yourls/hnof,NSFW(obviously) http://spankbang.com/iy3u/video/marica+hase+mirrors+edge,Good News ::Download WhatsApp 2.16.230 APK for Android – Latest Version,1
4,4,code free tyrande --->>> [Imgur](http://i.imgur.com/KlvssCl.png)\n\nfor you and your friend 2 codes for 4 dollars https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=UN4E27AG7BWKS\n\n2$... buy one directly from here: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=VP3S5HQRE7T7E\n,"No Advertising: Spam, referral links, unsolicited advertising, and promotional content are not allowed.",hearthstone,wow!! amazing reminds me of the old days.Well Do you desire a great spell caster and a herbal doctor to help you solve any problem you are going through? i am a proud testimony of what king favour solution temple has offered me. Contact him now at kingfavoursolutiontemple@yahoo.com You will be the next to testify.bye everyone,seek for lady for sex in around http://p77.pl/12yb9,must be watch movie https://sites.google.com/site/greatescape1963xx/-jagten-2012-full-movie,"We're streaming Pokemon Veitnamese Crystal RIGHT NOW, come watch https://www.twitch.tv/adandyguyinspace55.",1

In [35]:
df_test.head(5)

,row_id,body,rule,subreddit,positive_example_1,positive_example_2,negative_example_1,negative_example_2
0,2029,NEW RAP GROUP 17. CHECK US OUT https://soundcloud.com/user-125895482,"No Advertising: Spam, referral links, unsolicited advertising, and promotional content are not allowed.",hiphopheads,"Hey, guys, just wanted to drop in and invite you to my Pokémon cards/TCG Discord server: https://discord.gg/S9SbGSe \n\nEveryone is welcome, and don't forget to bring your love for Pokémon!",Cum Swallowing Hottie Katrina Kaif Cartoon Xvideo18+\nhttps://youtu.be/0FwHHqCPrag,SD Stream Eng - [Chelsea TV USA](http://soccerstreamsarena.com/chelsea-u23-vs-tottenham-u23-live-epl2-09-sep-2016/) \n\nMobile : Compatible With Android Puffin Browser,HD Streams: |[ENG HD Stoke vs Manchester United](http://livesport360.net/stoke-city-vs-manchester-united-2-n2173) Ad Overlays: 1 Mobile: Yes
1,2030,"Make your life comfortable. Get up to 15% Discount. Pain killers Like Roxycodone, Hydrocodone, Codeine, Percocet, Hydrocodone, Oxycodone and Lortab. Also get full treatment of Depression, Insomnia and other such problems with Adderall, Ativan, **[Xanax](http://onestoppharma.org)**, Mogadon, Modafinil and Many Others Treatments Online **Without Prescription at [onestoppharma.org](http://onestoppharma.org)**",No legal advice: Do not offer or request legal advice.,AskReddit,"Get a lawyer and get the security camera footage of the entire store for that day. Maybe someone put the ingredient in her salad on purpose because they knew she was allergic. They could be charged with manslaughter. However, this is very unlikely.","That isn't drastic. You tried reaching out to her directly. She avoided your calls/texts, and HUNG UP ON YOU as soon as she realized it was your voice on her work line. \n\nBitch stole your puppy - a puppy that you are raising to be sold for profit. Effectively, she stole your property. \n\nCall the police. ASAP.","So what are you going to do with the insurance money when the house ""accidentally"" burns down?","It's just for Austria & Germany. If you still need it, drop me a PM. I'm not sure if I'm allowed to name it here."
2,2031,Kickin' ass and selling underwear!\nJust made my account last night. You guys should do the same and follow up on my photos and more 😘\n\n\n[find me here❤️](http://www.pantydeal.com/member/Ineffable),"No Advertising: Spam, referral links, unsolicited advertising, and promotional content are not allowed.",gonewild,Good story my friend. Check out my blog at http://www.ink2quill.com/,If you know what exactly you need then you don't needa prescription. You can buy it online. I buy every medication I need during last 3 years online and can recommend it. http://cheapmarketmeds.com/ is a pharmacy where you can find high-quality Wellbutrin.,"CENTIPEDES\n\nSOME BASED PATRIOTS HAVE CREATED A BASED NEW SUB FOR THE_DON CONTENT\n\nhttps://www.reddit.com/r/The_Uncensored_Donald/\n\nIF YOU WANT FRESH CONTENT, KEK BLESSINGS AND MORE HIGH ENERGY DELIVERED TO YOU PAY THEM A VISIT AND SHITPOST THERE FOR STICKING IT TO A CERTAIN EDITING CANNIBAL",[So great! Thanks for sharing.](http://www.cheapsexynightgirls.com/2014/03/zoya-independent-call-girls-in-dubai.html)
3,2032,watch hooters best therein http://clickand.co/5agw-,"No Advertising: Spam, referral links, unsolicited advertising, and promotional content are not allowed.",personalfinance,"Earn 50,000 bonus points with Chase Sapphire Preferred®. Learn more at https://applynow.chase.com/FlexAppWeb/renderApp.do?PID=CFFD2&SPID=FHRJ&CELL=600V&MSC=1532571015 #sponsored","Cool, front page! I made this print along with a lot of other science and spaced themed stuff you can find here: http://2046printshop.com/\nIf you really want the Apollo print you can PM me, if I get enough requests I'll make another run of it.",[Full HD Movie Online Free](http://www.flickmaza.com/),* Karambit Black Pearl\n* 0.02137822 Float (unfortunate corner)\n* Non-Duped\n* Screenshot - http://imgur.com/a/Zvy5D\n* Metjm - http://s.metjm.net/0XymKVi.jpg\n* B/O - 500+ keys (Very Negotiable)\n* PC (500 keys) - https://imgur.com/a/5IWM3\n* C/O (485) - https://imgur.com/a/zgexV\n* My steam Acc. - https://steamcommunity.com/id/OfficialSnuffy/\n* Send me an offer here:\n* https://steamcommunity.com/tradeoffer/new/?partner=154014229&token=npsf8rwb
4,2033,bitches for free at this point show all http://ur.my/212hg,"No Advertising: Spam, referral links, unsolicited advertising, and promotional content are not allowed.",Showerthoughts,code free tyrande --->>> [Imgur](http://i.imgur.com/KlvssCl.png)\n\nfor you and your friend 2 codes for 4 dollars https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=UN4E27AG7BWKS\n\n2$... buy one directly from here: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=VP3S5HQRE7T7E\n,My trade link\nhttps://steamcommunity.com/tradeoffer/new/?partner=120138057&token=oswPVc-d,**HD** [ mio Stadium 102 HD](http://www.genti.stream/hd3.php) | Mobile Compatible\n,"Infographics is an incredible method for showing your businesses focal points. My newly created infographic is for Workers Compensation Lawyer Philadelphia, who are using it to advertise their business highlights in a clear and concise design.visit http://www.workerscompensationlawyer-philadelphia.com/ for more\n"

In [36]:
df_train.shape

(2029, 9)

In [37]:
df_train.columns.to_list()

['row_id',
 'body',
 'rule',
 'subreddit',
 'positive_example_1',
 'positive_example_2',
 'negative_example_1',
 'negative_example_2',
 'rule_violation']

In [38]:
import pandas as pd
null_or_empty_summary = {}
for col in df_train.columns:
    null_count = df_train[col].isna().sum()
    empty_count = (df_train[col] == "").sum()
    null_or_empty_summary[col] = {
        "null_count": null_count,
        "empty_string_count": empty_count
    }

summary_df = pd.DataFrame(null_or_empty_summary).T
print(summary_df)

                    null_count  empty_string_count
row_id                       0                   0
body                         0                   0
rule                         0                   0
subreddit                    0                   0
positive_example_1           0                   0
positive_example_2           0                   0
negative_example_1           0                   0
negative_example_2           0                   0
rule_violation               0                   0

In [39]:
import pandas as pd

def augment_rows(row):
    new_rows = []

    #1
    new_rows.append(row)


    #2
    swapped_neg = row.copy()
    swapped_neg["negative_example_1"], swapped_neg["negative_example_2"] = \
        row["negative_example_2"], row["negative_example_1"]
    new_rows.append(swapped_neg)


    # 3.
    swapped_pos = row.copy()
    swapped_pos["positive_example_1"], swapped_pos["positive_example_2"] = \
        row["positive_example_2"], row["positive_example_1"]
    new_rows.append(swapped_pos)



    # 4.
    swapped_pos = row.copy()
    swapped_pos["positive_example_1"], swapped_pos["positive_example_2"] = row["positive_example_2"], row["positive_example_1"]
    swapped_pos["negative_example_1"], swapped_pos["negative_example_2"] = row["negative_example_2"], row["negative_example_1"]
    new_rows.append(swapped_pos)
    

    # +2. Rule-based body <-> examples swap
    if row["rule_violation"] == 1:
        for col in ["negative_example_1", "negative_example_2"]:
            swapped = row.copy()
            swapped["body"], swapped[col] = row[col], row["body"]
            new_rows.append(swapped)
    else:
        for col in ["positive_example_1", "positive_example_2"]:
            swapped = row.copy()
            swapped["body"], swapped[col] = row[col], row["body"]
            new_rows.append(swapped)

    return new_rows

# Apply to all rows
augmented = []
for _, row in df_train.iterrows():
    augmented.extend(augment_rows(row))

augmented_df = pd.DataFrame(augmented)

augmented_df.shape

(12174, 9)

In [40]:
augmented_df.to_pickle("augmented_dataset_1*6_swaps_with_body_neg_n_pos_example.pkl")
# augmented_df = pd.read_pickle("augmented_dataset.pkl")

In [41]:
del df_train
import gc 
gc.collect()

0

In [42]:
augmented_df.head(4)

,row_id,body,rule,subreddit,positive_example_1,positive_example_2,negative_example_1,negative_example_2,rule_violation
0,0,Banks don't want you to know this! Click here to know more!,"No Advertising: Spam, referral links, unsolicited advertising, and promotional content are not allowed.",Futurology,"If you could tell your younger self something different about sex, what would that be?\n\ni AM IN A CONTEST TO WIN FUNDING FOR MY SEX POSITIVE FILM: VOTE HERE:\n\nhttp://sheknows.offerpop.com/campaign/813112/entry/v144417",hunt for lady for jack off in neighbourhood http://url.inmusi.com/gakq,Watch Golden Globe Awards 2017 Live Online in HD Coverage without ADS (VIP STREAMS)\n=\n\nHD STREAM QUALITY >>> [WATCH LINK1](http://forum.submitexpress.com/viewtopic.php?f=9&t=215858)\n=\n\nHD BROADCASTING QUALITY >>> [WATCH LINK1](http://forum.submitexpress.com/viewtopic.php?f=9&t=215858)\n=\n\nMobile Compatibility: YES\n=\n\nNO ADS | NO ADS | ADS\n=\n,"DOUBLE CEE x BANDS EPPS - ""BIRDS""\n\nDOWNLOAD/STREAM:\n\nhttp://music.theblacksmithed.com/download/birds/",0
0,0,Banks don't want you to know this! Click here to know more!,"No Advertising: Spam, referral links, unsolicited advertising, and promotional content are not allowed.",Futurology,"If you could tell your younger self something different about sex, what would that be?\n\ni AM IN A CONTEST TO WIN FUNDING FOR MY SEX POSITIVE FILM: VOTE HERE:\n\nhttp://sheknows.offerpop.com/campaign/813112/entry/v144417",hunt for lady for jack off in neighbourhood http://url.inmusi.com/gakq,"DOUBLE CEE x BANDS EPPS - ""BIRDS""\n\nDOWNLOAD/STREAM:\n\nhttp://music.theblacksmithed.com/download/birds/",Watch Golden Globe Awards 2017 Live Online in HD Coverage without ADS (VIP STREAMS)\n=\n\nHD STREAM QUALITY >>> [WATCH LINK1](http://forum.submitexpress.com/viewtopic.php?f=9&t=215858)\n=\n\nHD BROADCASTING QUALITY >>> [WATCH LINK1](http://forum.submitexpress.com/viewtopic.php?f=9&t=215858)\n=\n\nMobile Compatibility: YES\n=\n\nNO ADS | NO ADS | ADS\n=\n,0
0,0,Banks don't want you to know this! Click here to know more!,"No Advertising: Spam, referral links, unsolicited advertising, and promotional content are not allowed.",Futurology,hunt for lady for jack off in neighbourhood http://url.inmusi.com/gakq,"If you could tell your younger self something different about sex, what would that be?\n\ni AM IN A CONTEST TO WIN FUNDING FOR MY SEX POSITIVE FILM: VOTE HERE:\n\nhttp://sheknows.offerpop.com/campaign/813112/entry/v144417",Watch Golden Globe Awards 2017 Live Online in HD Coverage without ADS (VIP STREAMS)\n=\n\nHD STREAM QUALITY >>> [WATCH LINK1](http://forum.submitexpress.com/viewtopic.php?f=9&t=215858)\n=\n\nHD BROADCASTING QUALITY >>> [WATCH LINK1](http://forum.submitexpress.com/viewtopic.php?f=9&t=215858)\n=\n\nMobile Compatibility: YES\n=\n\nNO ADS | NO ADS | ADS\n=\n,"DOUBLE CEE x BANDS EPPS - ""BIRDS""\n\nDOWNLOAD/STREAM:\n\nhttp://music.theblacksmithed.com/download/birds/",0
0,0,Banks don't want you to know this! Click here to know more!,"No Advertising: Spam, referral links, unsolicited advertising, and promotional content are not allowed.",Futurology,hunt for lady for jack off in neighbourhood http://url.inmusi.com/gakq,"If you could tell your younger self something different about sex, what would that be?\n\ni AM IN A CONTEST TO WIN FUNDING FOR MY SEX POSITIVE FILM: VOTE HERE:\n\nhttp://sheknows.offerpop.com/campaign/813112/entry/v144417","DOUBLE CEE x BANDS EPPS - ""BIRDS""\n\nDOWNLOAD/STREAM:\n\nhttp://music.theblacksmithed.com/download/birds/",Watch Golden Globe Awards 2017 Live Online in HD Coverage without ADS (VIP STREAMS)\n=\n\nHD STREAM QUALITY >>> [WATCH LINK1](http://forum.submitexpress.com/viewtopic.php?f=9&t=215858)\n=\n\nHD BROADCASTING QUALITY >>> [WATCH LINK1](http://forum.submitexpress.com/viewtopic.php?f=9&t=215858)\n=\n\nMobile Compatibility: YES\n=\n\nNO ADS | NO ADS | ADS\n=\n,0

In [43]:
def make_context(row):
    return f"""
*discussions on this topic*:{row['subreddit']}
*rules of discussion*:{row['rule']}
*positive_examples(0)*:
1. {row['positive_example_1']}
2. {row['positive_example_2']}
*negative_examples(1)*:
1. {row['negative_example_1']}
2. {row['negative_example_2']}
*Direction for task*:
classify next statement accordingly.
"""

# Build new dataframe
new_df = pd.DataFrame({
    "context": augmented_df.apply(make_context, axis=1),
    "statement": augmented_df["body"],
    "target": augmented_df["rule_violation"]
})

In [44]:
new_df

,context,statement,target
0,"\n*discussions on this topic*:Futurology\n*rules of discussion*:No Advertising: Spam, referral links, unsolicited advertising, and promotional content are not allowed.\n*positive_examples(0)*:\n1. If you could tell your younger self something different about sex, what would that be?\n\ni AM IN A CONTEST TO WIN FUNDING FOR MY SEX POSITIVE FILM: VOTE HERE:\n\nhttp://sheknows.offerpop.com/campaign/813112/entry/v144417\n2. hunt for lady for jack off in neighbourhood http://url.inmusi.com/gakq\n*negative_examples(1)*:\n1. Watch Golden Globe Awards 2017 Live Online in HD Coverage without ADS (VIP STREAMS)\n=\n\nHD STREAM QUALITY >>> [WATCH LINK1](http://forum.submitexpress.com/viewtopic.php?f=9&t=215858)\n=\n\nHD BROADCASTING QUALITY >>> [WATCH LINK1](http://forum.submitexpress.com/viewtopic.php?f=9&t=215858)\n=\n\nMobile Compatibility: YES\n=\n\nNO ADS | NO ADS | ADS\n=\n\n2. DOUBLE CEE x BANDS EPPS - ""BIRDS""\n\nDOWNLOAD/STREAM:\n\nhttp://music.theblacksmithed.com/download/birds/\n*Direction for task*:\nclassify next statement accordingly.\n",Banks don't want you to know this! Click here to know more!,0
0,"\n*discussions on this topic*:Futurology\n*rules of discussion*:No Advertising: Spam, referral links, unsolicited advertising, and promotional content are not allowed.\n*positive_examples(0)*:\n1. If you could tell your younger self something different about sex, what would that be?\n\ni AM IN A CONTEST TO WIN FUNDING FOR MY SEX POSITIVE FILM: VOTE HERE:\n\nhttp://sheknows.offerpop.com/campaign/813112/entry/v144417\n2. hunt for lady for jack off in neighbourhood http://url.inmusi.com/gakq\n*negative_examples(1)*:\n1. DOUBLE CEE x BANDS EPPS - ""BIRDS""\n\nDOWNLOAD/STREAM:\n\nhttp://music.theblacksmithed.com/download/birds/\n2. Watch Golden Globe Awards 2017 Live Online in HD Coverage without ADS (VIP STREAMS)\n=\n\nHD STREAM QUALITY >>> [WATCH LINK1](http://forum.submitexpress.com/viewtopic.php?f=9&t=215858)\n=\n\nHD BROADCASTING QUALITY >>> [WATCH LINK1](http://forum.submitexpress.com/viewtopic.php?f=9&t=215858)\n=\n\nMobile Compatibility: YES\n=\n\nNO ADS | NO ADS | ADS\n=\n\n*Direction for task*:\nclassify next statement accordingly.\n",Banks don't want you to know this! Click here to know more!,0
0,"\n*discussions on this topic*:Futurology\n*rules of discussion*:No Advertising: Spam, referral links, unsolicited advertising, and promotional content are not allowed.\n*positive_examples(0)*:\n1. hunt for lady for jack off in neighbourhood http://url.inmusi.com/gakq\n2. If you could tell your younger self something different about sex, what would that be?\n\ni AM IN A CONTEST TO WIN FUNDING FOR MY SEX POSITIVE FILM: VOTE HERE:\n\nhttp://sheknows.offerpop.com/campaign/813112/entry/v144417\n*negative_examples(1)*:\n1. Watch Golden Globe Awards 2017 Live Online in HD Coverage without ADS (VIP STREAMS)\n=\n\nHD STREAM QUALITY >>> [WATCH LINK1](http://forum.submitexpress.com/viewtopic.php?f=9&t=215858)\n=\n\nHD BROADCASTING QUALITY >>> [WATCH LINK1](http://forum.submitexpress.com/viewtopic.php?f=9&t=215858)\n=\n\nMobile Compatibility: YES\n=\n\nNO ADS | NO ADS | ADS\n=\n\n2. DOUBLE CEE x BANDS EPPS - ""BIRDS""\n\nDOWNLOAD/STREAM:\n\nhttp://music.theblacksmithed.com/download/birds/\n*Direction for task*:\nclassify next statement accordingly.\n",Banks don't want you to know this! Click here to know more!,0
0,"\n*discussions on this topic*:Futurology\n*rules of discussion*:No Advertising: Spam, referral links, unsolicited advertising, and promotional content are not allowed.\n*positive_examples(0)*:\n1. hunt for lady for jack off in neighbourhood http://url.inmusi.com/gakq\n2. If you could tell your younger self something different about sex, what would that be?\n\ni AM IN A CONTEST TO WIN FUNDING FOR MY SEX POSITIVE FILM: VOTE HERE:\n\nhttp://sheknows.offerpop.com/campaign/813112/entry/v144417\n*negative_examples(1)*:\n1. DOUBLE CEE x BANDS EPPS - ""BIRDS""\n\nDOWNLOAD/STREAM:\n\nhttp://music.theblacksmithed.com/download/birds/\n2. Watch Golden Globe Awards 2017 Live Online in HD Coverage without ADS (VIP STREAMS)\n=\n\nHD STREAM QUALITY >>> [WATCH LINK1](http://forum.submitexpress.com/viewtopic.php?f=9&t=215858)\n=\n\nHD BROADCASTING QUALITY >>> [WATCH LINK1](http://forum.submitexpress.com/viewtopic.php?f=9&t=215858)\n=\n\nMobile Compatibility: YES\n=\n\nNO ADS | NO ADS | ADS\n=\n\n*Direction for task*:\nclassify next statement accordingly.\n",Banks don't want you to know this! Click here to know more!,0
0,"\n*discussions on this topic*:Futurology\n*rules of discussion*:No Advertising: Spam, referral links, unsolicited advertising, and promotional content are not allowed.\n*positive_examples(0)*:\n1. Banks don't want you to know this! Click here to know more!\n2. hunt for lady for jack off in neighbourhood http://url.inmusi.com/gakq\n*negative_examples(1)*:\n1. Watch Golden Globe Awards 2017 Live Online in HD Coverage without ADS (VIP STREAMS)\n=\n\nHD STREAM QUALITY >>> [WATCH LINK1](http://forum.submitexpress.com/viewtopic.php?f=9&t=215858)\n=\n\nHD BROADCASTING QUALITY >>> [WATCH LINK1](http://forum.submitexpress.com/viewtopic.php?f=9&t=215858)\n=\n\nMobile Compatibility: YES\n=\n\nNO ADS | NO ADS | ADS\n=\n\n2. DOUBLE CEE x BANDS EPPS - ""BIRDS""\n\nDOWNLOAD/STREAM:\n\nhttp://music.theblacksmithed.com/download/birds/\n*Direction for task*:\nclassify next statement accordingly.\n","If you could tell your younger self something different about sex, what would that be?\n\ni AM IN A CONTEST TO WIN FUNDING FOR MY SEX POSITIVE FILM: VOTE HERE:\n\nhttp://sheknows.offerpop.com/campaign/813112/entry/v144417",0
...,...,...,...
2028,"\n*discussions on this topic*:legaladvice\n*rules of discussion*:No legal advice: Do not offer or request legal advice.\n*positive_examples(0)*:\n1. [Yes, it is. In the USA, at least](https://www.law.cornell.edu/uscode/text/18/2256). \n \nTo put it bluntly, child porn must either show genitals or be sexual in nature. Underwear covers the same as a bathing suit and if all they are doing is standing there, it's perfectly legal. \n \nPlease be aware that I'm only pointing out a fact, **not** defending that scumbag. \n2. Never pay a civil demand. \n\nIt's a bluff and no company will ever sue anybody over an amount as small as $500.00\n\n\n*negative_examples(1)*:\n1. Steal a car from an elderly person who won't notice it missing, roll without plates. Either way I'm gonna run you down and get away with it. \n2. Where is there a site that still works where you can jump the GPS. Is there a FAQ to do this with iPhone or Mac?\n*Direction for task*:\nclassify next statement accordingly.\n","> CA is an at fault state so they will not be able to recover anything from your policy/you unless you were found to be at fault.\n\nI'm not certain I agree with this point fully. The resulting civil suit would not be directly related to any of CA's road laws; while not being at fault is evidence in OP's favor, other factors could potentially sway the jury enough since it's not a matter of Reasonable Doubt.",1
2028,"\n*discussions on this topic*:legaladvice\n*rules of discussion*:No legal advice: Do not offer or request legal advice.\n*positive_examples(0)*:\n1. Never pay a civil demand. \n\nIt's a bluff and no company will ever sue anybody over an amount as small as $500.00\n\n\n2. [Yes, it is. In the USA, at least](https://www.law.cornell.edu/uscode/text/18/2256). \n \nTo put it bluntly, child porn must either show genitals or be sexual in nature. Underwear covers the same as a bathing suit and if all they are doing is standing there, it's perfectly legal. \n \nPlease be aware that I'm only pointing out a fact, **not** defending that scumbag. \n*negative_examples(1)*:\n1. Where is there a site that still works where you can jump the GPS. Is there a FAQ to do this with iPhone or Mac?\n2. Steal a car from an elderly person who won't notice it missing, roll without plates. Either way I'm gonna run you down and get away with it. \n*Direction for task*:\nclassify next statement accordingly.\n","> CA is an at fault state so they will not be able to recover anything from your policy/you unless you were found to be at fault.\n\nI'm not certain I agree with this point fully. The resulting civil suit would not be directly related to any of CA's road laws; while not being at fault is evidence in OP's favor, other factors could potentially sway the jury enough since it's not a matter of Reasonable Doubt.",1
2028,"\n*discussions on this topic*:legaladvice\n*rules of discussion*:No legal advice: Do not offer or request legal advice.\n*positive_examples(0)*:\n1. Never pay a civil demand. \n\nIt's a bluff and no company will ever sue anybody over an amount as small as $500.00\n\n\n2. [Yes, it is. In the USA, at least](https://www.law.cornell.edu/uscode/text/18/2256). \n \nTo put it bluntly, child porn must either show genitals or be sexual in nature. Underwear covers the same as a bathing suit and if all they are doing is standing there, it's perfectly legal. \n \nPlease be aware that I'm only pointing out a fact, **not** defending that scumbag. \n*negative_examples(1)*:\n1. Steal a car from an elderly person who won't notice it missing, roll without plates. Either way I'm gonna run you down and get away with it. \n2. Where is there a site that still works where you can jump the GPS. Is there a FAQ to do this with iPhone or Mac?\n*Direction for task*:\nclassify next statement accordingly.\n","> CA is an at fault state so they will not be able to recover anything from your policy/you unless you were found to be at fault.\n\nI'm not certain I agree with this point fully. The resulting civil suit would not be directly related to any of CA's road laws; while not being at fault is evidence in OP's favor, other factors could potentially sway the jury enough since it's not a matter of Reasonable Doubt.",1
2028,"\n*discussions on this topic*:legaladvice\n*rules of discussion*:No legal advice: Do not offer or request legal advice.\n*positive_examples(0)*:\n1. [Yes, it is. In the USA, at least](https://www.law.cornell.edu/uscode/text/18/2256). \n \nTo put it bluntly, child porn must either show genitals or be sexual in nature. Underwear covers the same as a bathing suit and if all they are doing is standing there, it's perfectly legal. \n \nPlease be aware that I'm only pointing out a fact, **not** defending that scumbag. \n2. Never pay a civil demand. \n\nIt's a bluff and no company will ever sue anybody over an amount as small as $500.00\n\n\n*negative_examples(1)*:\n1. > CA is an at fault state so they will not be able to recover anything from your policy/you unless you were found to be at fault.\n\nI'm not certain I agree with this point fully. The resulting civil suit would not be directly related to any of CA's road laws; while not being at fault is evidence in OP's favor, other factors could potentially sway the jury enough since it's not a matter of Reasonable Doubt.\n2. Steal a car from an elderly person who won't notice it missing, roll without plates. Either way I'm gonna run you down and get away with it. \n*Direction for task*:\nclassify next statement accordingly.\n",Where is there a site that still works where you can jump the GPS. Is there a FAQ to do this with iPhone or Mac?,1
2028,"\n*discussions on this topic*:legaladvice\n*rules of discussion*:No legal advice: Do not offer or request legal advice.\n*positive_examples(0)*:\n1. [Yes, it is. In the USA, at least](https://www.law.cornell.edu/uscode/text/18/2256). \n \nTo put it bluntly, child porn must either show genitals or be sexual in nature. Underwear covers the same as a bathing suit and if all they are doing is standing there, it's perfectly legal. \n \nPlease be aware that I'm only pointing out a fact, **not** defending that scumbag. \n2. Never pay a civil demand. \n\nIt's a bluff and no company will ever sue anybody over an amount as small as $500.00\n\n\n*negative_examples(1)*:\n1. Where is there a site that still works where you can jump the GPS. Is there a FAQ to do this with iPhone or Mac?\n2. > CA is an at fault state so they will not be able to recover anything from your policy/you unless you were found to be at fault.\n\nI'm not certain I agree with this point fully. The resulting civil suit would not be directly related to any of CA's road laws; while not being at fault is evidence in OP's favor, other factors could potentially sway the jury enough since it's not a matter of Reasonable Doubt.\n*Direction for task*:\nclassify next statement accordingly.\n","Steal a car from an elderly person who won't notice it missing, roll without plates. Either way I'm gonna run you down and get away with it.",1

In [45]:
new_df.to_pickle("augmented_dataset_context_statement_target.pkl")
# new_df = pd.read_pickle("augmented_dataset_context_statement_target.pkl")

In [46]:
del augmented_df
import gc 
gc.collect()

0

In [47]:
df_aug_context_statement_target = new_df

In [48]:
import numpy as np
from sklearn.model_selection import train_test_split

# Shuffle dataframe
df_aug_context_statement_target = df_aug_context_statement_target.sample(frac=1, random_state=42).reset_index(drop=True)

# Create numpy arrays
X = df_aug_context_statement_target[["context", "statement"]].values   # shape (n_samples, 2)
Y = df_aug_context_statement_target["target"].values                   # shape (n_samples,)

# Train/test split (90:10) with stratification
X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.1, random_state=42, stratify=Y
)

print("Train size:", X_train.shape, "Test size:", X_test.shape)
print("Class distribution in Y_train:", Y_train.shape)
print("Class distribution in Y_test:", Y_test.shape)

Train size: (10956, 2) Test size: (1218, 2)
Class distribution in Y_train: (10956,)
Class distribution in Y_test: (1218,)

In [49]:
df_aug_context_statement_target

,context,statement,target
0,\n*discussions on this topic*:legaladvice\n*rules of discussion*:No legal advice: Do not offer or request legal advice.\n*positive_examples(0)*:\n1. He should be able to handle stress better and not mistreat you. FYI stress get to everyone but no one acts this dickish unless they already were a dick. Dont write the letter tell him its over amd get a roomate to help pay house bills. If he refuses to leave contact a lwayer to see about finding options to evict him / what are your options. He pretty much is a deadweight. Don't let him sink/drown you. \n2. If you are in the U.S. then the prison has to provide medication prescribed. If they are not cooperating then you will need to sue. Your local ACLU might be able to help or refer you to someone that can. \n*negative_examples(1)*:\n1. Counter-sue on behalf of the birds in your yard for harassment. You could also use the fact that the cat was clearly hammered when she climbed the tree or she would have landed on her feet as a defense. \n\nQuestion though - could Fluffy (now to be known as Gimpy) claim attractive nuisance based on the clearing begging to be climbed tree? Maybe to be safe OP should install little cat sized trampolines under all his trees.\n2. Is this 100% legal tho? Are their any copyright laws againt pirating board games lol\n*Direction for task*:\nclassify next statement accordingly.\n,"So she's down to handwriting? I guess one could always burn a letter, much better than bleaching an e-mail.",1
1,"\n*discussions on this topic*:legaladvice\n*rules of discussion*:No legal advice: Do not offer or request legal advice.\n*positive_examples(0)*:\n1. You should also understand that *consensual adult* incest is both legal and harmless; see http://marriage-equality.blogspot.com\n2. Oh look, a stupid person!\n\nIf you're talking about the US, the states that do recognize common law marriages all require parties to have a marriage agreement and stated intent. You can't just suddenly be declared ""married"" without wanting to be married. The one exception is New Hampshire, and they only can consider it after the death of one of the parties. \n*negative_examples(1)*:\n1. People need to remember the gentle art of the Punch to the Dick for times like this. Guy tries to take your sign? Punch to the Dick.\n2. First off, you need a lawyer because you will be suing the kid that did this.\n\nSecond, you need to contact the school via registered mail with a deadline for a response from them.\n\nIf they don't respond then you go to the school board and local media...\n\nKeep in mind you will be taken a lot more seriously once you file a suit on the student that caused this.\n*Direction for task*:\nclassify next statement accordingly.\n","not genocide, just the execution of innocent civilians related to accused terrorists.",1
2,"\n*discussions on this topic*:soccerstreams\n*rules of discussion*:No Advertising: Spam, referral links, unsolicited advertising, and promotional content are not allowed.\n*positive_examples(0)*:\n1. that lady let give ass with you http://https://x5.re/KZY4\n2. code free tyrande --->>> [Imgur](http://i.imgur.com/KlvssCl.png)\n\nfor you and your friend 2 codes for 4 dollars https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=UN4E27AG7BWKS\n\n2$... buy one directly from here: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=VP3S5HQRE7T7E\n\n*negative_examples(1)*:\n1. SD Eng : http://sportsleague.me/crystal-palace-vs-manchester-united-live-english-fa-cup-21-may-2016/\n\n* No mobile compatibility | Decent Reliable Stream\n2. HD Stream: [English stream](http://www.uclstreaming.ml) Mobile: yes\n*Direction for task*:\nclassify next statement accordingly.\n",SD Streams:| [ENG stream 1 ](http://www.multi-sports.eu/2.html) | \nMobile Compatibility: NO \n\nstream goes live 5 minutes before kick off,0
3,"\n*discussions on this topic*:news\n*rules of discussion*:No legal advice: Do not offer or request legal advice.\n*positive_examples(0)*:\n1. ####ITS A PRETTY CLASSIC CASE OF OVEREXTENDING. LIKE WHEN I FLIRTED WITH MY NEPHEWS GORGEOUS GAMECATT LOOKALIKE PHYSICAL THERAPIST AND GOT HER NUMBER BUT SHE ENDED UP CALLING THE COPS AFTER I TEXTED HER A SLICE OF EROTIC WHIMSY TELLING HER I WAS GOING TO FILL HER RECTUM WITH TEETH WHICH SHE MISINTERPRETED AS ME THREATENING TO BITE HER ASS####\n2. You don't get to half-ass a case just because the client is a scumbag. That's actually an ethics violation in and if itself. \n*negative_examples(1)*:\n1. He asked what a CON would be to refinancing. I believe having your vehicle repo'd instantly if you miss a payment when refinancing is a huge fucking CON. Pos.\n2. Hahahaha we are very supportive of your right to speak freely; however, there's a line between genuine criticism and outright partisan hysteria. Your sub screams fire in a movie theatre on a daily basis - that's not speech protected by the First Amendment. 'Retracting' a story a week after it goes viral is not an adequate remedy - the damage has already been done and retractions don't go viral. Btw, a retraction is an admission for publishing Fake News \n*Direction for task*:\nclassify next statement accordingly.\n","I know for sure the women beating thing is exaggerated, though killing gay people is wrong. The wife beating can only be done with a stick (about the size of a toothbrush) and I can't leave any marks of any kind. So... It's more of a ceremonial thing. Just uh, you gotta be more accurate with your criticisms.",0
4,"\n*discussions on this topic*:funny\n*rules of discussion*:No Advertising: Spam, referral links, unsolicited advertising, and promotional content are not allowed.\n*positive_examples(0)*:\n1. Want to make some spare change?\n\nhttp://www.swagbucks.com/refer/bethany1699\n2. [2 tickets to Drake & Future - $350 - Free shipping\n\nAug. 27 in Tampa]\n(http://www.ebay.com/itm/Drake-Future-Summer-Sixteen-Tour-8-27-2016-Tampa-FL-2-Tickets-/291794445858?hash=item43f04de622:g:1A8AAOSwepJXYwD6)\n*negative_examples(1)*:\n1. [Full HD Movie Online Free](http://www.flickmaza.com/)\n2. We provide high quality business email database marketing lists and B2B Marketing Database services. Also Check our Data Appending Services in detail here\n*Direction for task*:\nclassify next statement accordingly.\n",[Few people know the dark history of elves as a Cold War weapon.](http://txt.do/d5bc3) (text file),0
...,...,...,...
12169,"\n*discussions on this topic*:legaladvice\n*rules of discussion*:No legal advice: Do not offer or request legal advice.\n*positive_examples(0)*:\n1. You should also understand that *consensual adult* incest is both legal and harmless; see http://marriage-equality.blogspot.com\n2. [Yes, it is. In the USA, at least](https://www.law.cornell.edu/uscode/text/18/2256). \n \nTo put it bluntly, child porn must either show genitals or be sexual in nature. Underwear covers the same as a bathing suit and if all they are doing is standing there, it's perfectly legal. \n \nPlease be aware that I'm only pointing out a fact, **not** defending that scumbag. \n*negative_examples(1)*:\n1. Sell your Herman Miller stock. There are going to be class-actions.\n\nBut worker's comp will cover your heart transplant.\n2. Next time she comes at you have your phone on, then stab a bitch.\n*Direction for task*:\nclassify next statement accordingly.\n","Yeah Id like to see some law on this also, cause I still have keys from a place i rented 5 years ago. Should I expect a back rent bill for $60,000 at some point.\n\nKeys have nothing to do with possession. The worst he could do is charge for changing the locks. ON the back side of that if the LL entered the property during that time period without notice wouldnt he be in violation of law as well?",1
12170,"\n*discussions on this topic*:NSFW_GIF\n*rules of discussion*:No Advertising: Spam, referral links, unsolicited advertising, and promotional content are not allowed.\n*positive_examples(0)*:\n1. check out nice girl for fuck in next door http://painacorli1975.tumblr.com\n2. Make your life comfortable. Get up to 15% Discount. Pain killers Like Roxycodone, Hydrocodone, Codeine, Percocet, Hydrocodone, Oxycodone and Lortab. Also get full treatment of Depression, Insomnia and other such problems with Adderall, Ativan, **[Xanax](http://onestoppharma.org)**, Mogadon, Modafinil and Many Others Treatments Online **Without Prescription at [onestoppharma.org](http://onestoppharma.org)**\n*negative_examples(1)*:\n1. SD Stream [Cameroon vs Guinea-Bissau ENG Stream](http://www.cr7live.ml/p/blog-page_15.html) | Ad Overlays: 2| Pop: 2| Mobile: No |\n2. i have watch episode 7 yesterday , [great http://epseries.com/game-of-thrones-saison-6-episode-7.html]\n*Direction for task*:\nclassify next statement accordingly.\n",[[Staci Carr - You're my desire|http://www.sextvx.com/en/video/702613/staci-carr-youre-my-desire-20-feb]],1
12171,"\n*discussions on this topic*:sex\n*rules of discussion*:No Advertising: Spam, referral links, unsolicited advertising, and promotional content are not allowed.\n*positive_examples(0)*:\n1. Giving away Tyrande code for 80g quest add me Kaiba1488#2995 EU.\n\n2. roadrunner support number 1-844-659-1035 is in existence for the technical support related to your roadrunner email issue.you can contact us any time on our road runner support number.we believe in provide genuine support to our clients.so for any kind of issue related to your roadrunner email you can contact road runner 1-844-659-1035.we have a good team for technical associate so please contact us on our roadrunner support 1-844-659-1035\nhttp://www.roadrunnersupportnumber.com/\n\n*negative_examples(1)*:\n1. [15 Amazing Hidden Features Of Google Search You Probably Don’t Know](http://www.madpeoples.com/2017/01/02 No one would argue the fact that Google is one of the most useful sihttp://www.madpeoples.com/2016/12/31/15-amazing-hidden-features-of-google-search-you-probably-dont-know/tes on the Internet. Unfortunately, most people only use about...?utm_source=reddit&utm_campaign=samreen&utm_medium=cpc)\n2. Must Watch : https://www.youtube.com/watch?v=dQoedIV8LXo\n*Direction for task*:\nclassify next statement accordingly.\n",look up in for sluts your town laying on http://url.inmusi.com/gakq,0
12172,"\n*discussions on this topic*:legaladvice\n*rules of discussion*:No legal advice: Do not offer or request legal advice.\n*positive_examples(0)*:\n1. Well first you have to figure out if there is even a way that you can do such an agreement and you have to talk to a lawyer about that. \n2. Public School? You are under no legal obligation to pay anything.\n*negative_examples(1)*:\n1. Simple solution, if forced to perform such surgeries botch them and let the insurance company fight it out. Forcing a doctor to do something they don't want to do is a monumentally stupid idea.\n2. At parties, I only put rohypnol in my *own* drinks, for attention.\n*Direction for task*:\nclassify next statement accordingly.\n","I just lurk here and I'm not a lawyer at all, but why don't you just ""lose"" your current debit card so they don't have the right numbers and then just not answer their calls.",1
12173,"\n*discussions on this topic*:pokemongo\n*rules of discussion*:No Advertising: Spam, referral links, unsolicited advertising, and promotional content are not allowed.\n*positive_examples(0)*:\n1. Our Barco Users List Users Email Database helps you reach out directly to the IT decision makers and technology companies using Barco Users List Application. As our Barco Users List Users Lists are opt-in, accurate and verified, it’s the best way to reach out to the end users and top IT Executives using Barco Users List Application from various Industries across the globe. \n2. 240K if ur interested \nhttps://steamcommunity.com/tradeoffer/new/?partner=2323875&token=QxEkBN1-\n*negative_examples(1)*:\n1. I just found that you can get 100 000 Pokemon GO coins completely for free! Grab it now! http://pokegobonus.com/\n2. this is a goood movie watch it now\n\nvisit us in our blog \n\nhttp://moviesgalaxi.blogspot.com/\n*Direction for task*:\nclassify next statement accordingly.\n",###HD [Live Stream](http://howtowatchstream.com/)\nPC | Laptop | Android | Iphone | MAc | Windows,1

In [50]:
print("Class distribution in Y_train:", Y_train.shape)
print("Class distribution in Y_test:", Y_test.shape)

Class distribution in Y_train: (10956,)
Class distribution in Y_test: (1218,)

In [51]:
import tensorflow as tf
from transformers import DistilBertTokenizerFast, TFDistilBertForSequenceClassification
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import pandas as pd
import numpy as np
tokenizer = DistilBertTokenizerFast.from_pretrained("distilbert-base-uncased")

In [52]:
all_lengths = df_aug_context_statement_target.apply(lambda row: len(tokenizer(row['context'], row['statement'])['input_ids']), axis=1)
print("Max length:", all_lengths.max())
print("Average length:", all_lengths.mean())

Token indices sequence length is longer than the specified maximum sequence length for this model (643 > 512). Running this sequence through the model will result in indexing errors

Max length: 643
Average length: 309.4021685559389

In [53]:

MAX_LEN = 512

def tokenize(sent1, sent2, labels):
    encodings = tokenizer(
        sent1.tolist(),  # convert numpy array to list
        sent2.tolist(),
        truncation=True,
        padding="max_length",
        max_length=MAX_LEN,
        return_tensors="tf"
    )
    return encodings["input_ids"], encodings["attention_mask"], tf.convert_to_tensor(labels, dtype=tf.int32)

# If X_train and X_test are numpy arrays of shape (num_examples, 2)
train_input_ids, train_attention, train_labels = tokenize(
    X_train[:, 0],  # statement1
    X_train[:, 1],  # statement2
    Y_train         # labels
)

val_input_ids, val_attention, val_labels = tokenize(
    X_test[:, 0],  # statement1
    X_test[:, 1],  # statement2
    Y_test         # labels
)

# =====================================
# Build tf.data.Dataset
# =====================================
train_ds = tf.data.Dataset.from_tensor_slices(({
        "input_ids": train_input_ids,
        "attention_mask": train_attention
    }, train_labels)).shuffle(1000).batch(16)

val_ds = tf.data.Dataset.from_tensor_slices(({
        "input_ids": val_input_ids,
        "attention_mask": val_attention
    }, val_labels)).batch(16)

device_name = "GPU" if tf.config.list_physical_devices("GPU") else "CPU"
print("Using device:", device_name)

Using device: CPU

In [54]:
model = TFDistilBertForSequenceClassification.from_pretrained("distilbert-base-uncased", num_labels=2)

TensorFlow and JAX classes are deprecated and will be removed in Transformers v5. We recommend migrating to PyTorch classes or pinning your version of Transformers.

TypeError: 'builtins.safe_open' object is not iterable

In [ ]:

# =====================================
# 5. Compile Model
# =====================================
optimizer = tf.keras.optimizers.Adam(learning_rate=2e-5)
loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
metric = tf.keras.metrics.SparseCategoricalAccuracy("accuracy")

model.compile(optimizer=optimizer, loss=loss, metrics=[metric])

# =====================================
# 6. Train
# =====================================
EPOCHS = 3
history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=EPOCHS
)

# =====================================
# 7. Evaluate
# =====================================
val_preds = model.predict(val_ds).logits
val_preds = np.argmax(val_preds, axis=1)
acc = accuracy_score(Y_test, val_preds)
print("Validation Accuracy:", acc)

  2025-09-22T10:27:25.037572Z  WARN  Reqwest(reqwest::Error { kind: Request, url: "https://transfer.xethub.hf.co/xorbs/default/ab7f5f7c1eed0ce317ed7dec59e69e1894a72b8440dd20395037f1908e4e8866?X-Xet-Signed-Range=bytes%3D0-61136276&X-Xet-Session-Id=01K5RFCJ5WPCN32T2KJ8P69QHX&Expires=1758540414&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly90cmFuc2Zlci54ZXRodWIuaGYuY28veG9yYnMvZGVmYXVsdC9hYjdmNWY3YzFlZWQwY2UzMTdlZDdkZWM1OWU2OWUxODk0YTcyYjg0NDBkZDIwMzk1MDM3ZjE5MDhlNGU4ODY2P1gtWGV0LVNpZ25lZC1SYW5nZT1ieXRlcyUzRDAtNjExMzYyNzYmWC1YZXQtU2Vzc2lvbi1JZD0wMUs1UkZDSjVXUENOMzJUMktKOFA2OVFIWCIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc1ODU0MDQxNH19fV19&Signature=dnofTO9vjkWJDTWGcbkY~-r11SMd-JyDgbVvkvx7mW8LBkboGmuuJQPyzYPjHE-Vbqo0ww1422MlicgD-BJTVN99tDJ-yhbnapKTSDg~hi4ln3jgMu-OSaeyFSXPhkSDF0lCGUEhQT06T7hokk4nniY24lSFK1TcmIV9soZWBuynzKkr4n6bl5gJz-AaFXd~gBD98svXlcxaZpQdychTmzl04MiEDhvKEATVo80n-6xoga4-hIHZLKQdIR3e3K7we972lBT4qTQn-Dg-cmF52MWUJ2LvR7wN7GS7XLCricBBpitudQHsPnC4lNAUbfpMEK~Kj-XprvuKtTltB0M0dg__&Key-Pair-Id=K2L8F4GPSG1IFC", source: hyper_util::client::legacy::Error(SendRequest, hyper::Error(IncompleteMessage)) }). Retrying...
    at /home/runner/work/xet-core/xet-core/cas_client/src/http_client.rs:233

  2025-09-22T10:27:25.037647Z  WARN  Retry attempt #0. Sleeping 1.069139906s before the next attempt
    at /root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/reqwest-retry-0.7.0/src/middleware.rs:171

  2025-09-22T10:27:25.043787Z  WARN  Reqwest(reqwest::Error { kind: Request, url: "https://transfer.xethub.hf.co/xorbs/default/ede5feb7c2c3c86a257381efd075e4ac0c4c4762420f03b3d0d242d586ee81ca?X-Xet-Signed-Range=bytes%3D56106538-63419467&X-Xet-Session-Id=01K5RFCJ5WPCN32T2KJ8P69QHX&Expires=1758540414&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly90cmFuc2Zlci54ZXRodWIuaGYuY28veG9yYnMvZGVmYXVsdC9lZGU1ZmViN2MyYzNjODZhMjU3MzgxZWZkMDc1ZTRhYzBjNGM0NzYyNDIwZjAzYjNkMGQyNDJkNTg2ZWU4MWNhP1gtWGV0LVNpZ25lZC1SYW5nZT1ieXRlcyUzRDU2MTA2NTM4LTYzNDE5NDY3JlgtWGV0LVNlc3Npb24tSWQ9MDFLNVJGQ0o1V1BDTjMyVDJLSjhQNjlRSFgiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE3NTg1NDA0MTR9fX1dfQ__&Signature=vUtyQvfAabytcLN72q4XDpuN19PsXx297WhB0xahdS6DgJDhylzmpudeVxPLWuAmPLZ25E-M6oYh7dXgHulvbvK6buhbl97R4dLP5KMI-cDBPiDQhVXjBGrUwneGr3fpktUD6lOQnKqk8BVwCmLUiRcnXMpetM-a5QyyKZNgw4jj6CWOyuCJcty6r6dzIkecCswxFV9SCp12WABPqdxdAkCCsint~NA-UFZXdUEaHceIYLIEBelFe9HJGXXTPrrt5cOqGyxVjOlAGkQ6YYAXP0~w4bxnWZpMvvCWEV-WveVxCt4YepqFLTimeFGVmuDr6bw7QjCtyrDvuuwaOFD75w__&Key-Pair-Id=K2L8F4GPSG1IFC", source: hyper_util::client::legacy::Error(SendRequest, hyper::Error(IncompleteMessage)) }). Retrying...
    at /home/runner/work/xet-core/xet-core/cas_client/src/http_client.rs:233

  2025-09-22T10:27:25.043838Z  WARN  Reqwest(reqwest::Error { kind: Request, url: "https://transfer.xethub.hf.co/xorbs/default/ede5feb7c2c3c86a257381efd075e4ac0c4c4762420f03b3d0d242d586ee81ca?X-Xet-Signed-Range=bytes%3D17893486-26747619&X-Xet-Session-Id=01K5RFCJ5WPCN32T2KJ8P69QHX&Expires=1758540414&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly90cmFuc2Zlci54ZXRodWIuaGYuY28veG9yYnMvZGVmYXVsdC9lZGU1ZmViN2MyYzNjODZhMjU3MzgxZWZkMDc1ZTRhYzBjNGM0NzYyNDIwZjAzYjNkMGQyNDJkNTg2ZWU4MWNhP1gtWGV0LVNpZ25lZC1SYW5nZT1ieXRlcyUzRDE3ODkzNDg2LTI2NzQ3NjE5JlgtWGV0LVNlc3Npb24tSWQ9MDFLNVJGQ0o1V1BDTjMyVDJLSjhQNjlRSFgiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE3NTg1NDA0MTR9fX1dfQ__&Signature=H0w4YIqYzAFVJpUcZno95l06A06OfLPT3Uc04uIOlun6Zg~2~DXizOREN-7Ls~iAYnwEJrs3XhtvLHW29~MGuXva39vkky53guloa74VyL0RWHoDmtbZMy4T5CGMYvQ1HPHtRnwrJIyPfLx3RAxwL8HPUnMMtPKCQivInNDqYOiIhpmR4bCz0dbrVu75qbtzc-mc5TlrKKDrleo0zI1GOOnA8la8DmfRgS3KlDrO-McVF-cf65N3koAFplt5MtpPHbYaG~xz8HUJ9zKpZyA-gn94jpv1Ijw79k71DLtGsXqVwp-jRwVX14c2PXWPf30gbYJ0SHVlTguqslqWWrIn0A__&Key-Pair-Id=K2L8F4GPSG1IFC", source: hyper_util::client::legacy::Error(SendRequest, hyper::Error(IncompleteMessage)) }). Retrying...
    at /home/runner/work/xet-core/xet-core/cas_client/src/http_client.rs:233

  2025-09-22T10:27:25.043932Z  WARN  Retry attempt #0. Sleeping 61.080299ms before the next attempt
    at /root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/reqwest-retry-0.7.0/src/middleware.rs:171

  2025-09-22T10:27:25.043955Z  WARN  Retry attempt #0. Sleeping 83.789019ms before the next attempt
    at /root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/reqwest-retry-0.7.0/src/middleware.rs:171

  2025-09-22T10:27:25.054704Z  WARN  Reqwest(reqwest::Error { kind: Request, url: "https://transfer.xethub.hf.co/xorbs/default/ede5feb7c2c3c86a257381efd075e4ac0c4c4762420f03b3d0d242d586ee81ca?X-Xet-Signed-Range=bytes%3D31417202-33545322&X-Xet-Session-Id=01K5RFCJ5WPCN32T2KJ8P69QHX&Expires=1758540414&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly90cmFuc2Zlci54ZXRodWIuaGYuY28veG9yYnMvZGVmYXVsdC9lZGU1ZmViN2MyYzNjODZhMjU3MzgxZWZkMDc1ZTRhYzBjNGM0NzYyNDIwZjAzYjNkMGQyNDJkNTg2ZWU4MWNhP1gtWGV0LVNpZ25lZC1SYW5nZT1ieXRlcyUzRDMxNDE3MjAyLTMzNTQ1MzIyJlgtWGV0LVNlc3Npb24tSWQ9MDFLNVJGQ0o1V1BDTjMyVDJLSjhQNjlRSFgiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE3NTg1NDA0MTR9fX1dfQ__&Signature=NKlUAVRmZ2v7vdhuKcfrpdZ7GhjXlpBJ4DmeQyDgCYRYdTbtylncHiv-07vRZJUXcXf8gwnMxT0J1EnbQtM1B1yuOKI3XJe1C05RGoB3N~j2qqkYo3zGnQhqQi5j7bUGILvwd3eluHrsKQzetlBph8sQevqte4sgu~CXpTuvb66jKpqWcgYN~ce1TX7-Nj7DT2DDYgZp8aljhy-LoV-tof-mxfHRVD8trXDkRJsj8-SqhLApCotI7gzfBn-p5S4DPPA6FFmV46OezAPjOwZm2Ch9m32vk-qofJl1t9M0Zq3KHb53-684XSIhDRrEBrm084pACtePGbHtHnka6MNqfg__&Key-Pair-Id=K2L8F4GPSG1IFC", source: hyper_util::client::legacy::Error(SendRequest, hyper::Error(IncompleteMessage)) }). Retrying...
    at /home/runner/work/xet-core/xet-core/cas_client/src/http_client.rs:233

  2025-09-22T10:27:25.054738Z  WARN  Retry attempt #0. Sleeping 1.055427501s before the next attempt
    at /root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/reqwest-retry-0.7.0/src/middleware.rs:171

  2025-09-22T10:27:25.060394Z  WARN  Reqwest(reqwest::Error { kind: Request, url: "https://transfer.xethub.hf.co/xorbs/default/49145aa3ad9c46865a915641d235550644c6e520045d1b50851678ec241589df?X-Xet-Signed-Range=bytes%3D72361-1480152&X-Xet-Session-Id=01K5RFCJ5WPCN32T2KJ8P69QHX&Expires=1758540414&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly90cmFuc2Zlci54ZXRodWIuaGYuY28veG9yYnMvZGVmYXVsdC80OTE0NWFhM2FkOWM0Njg2NWE5MTU2NDFkMjM1NTUwNjQ0YzZlNTIwMDQ1ZDFiNTA4NTE2NzhlYzI0MTU4OWRmP1gtWGV0LVNpZ25lZC1SYW5nZT1ieXRlcyUzRDcyMzYxLTE0ODAxNTImWC1YZXQtU2Vzc2lvbi1JZD0wMUs1UkZDSjVXUENOMzJUMktKOFA2OVFIWCIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc1ODU0MDQxNH19fV19&Signature=py5gV0PVqk6H-O-mmkwtPvXHF3i0l5qDZDt7O87aqI8LmNoOkYsG9Oj91Dy19k6pnEYj0HM6PG7K8Dmd2tSRaXPoWHMnJeVY0PUeZhrmlvtuHCaKVXpha02OwzQRIgrgYDLki3nsHUA8ehRo6ElVrlAL7jeZCAJ3KxqUjOTFcX6TsCHBGaTN-77hxlJGkxg~xRKdLrgzhi4KgEgwv9ZLY0FSOGA9k1xG-itNZbrnX1xsq7YkmSJeAKtgjozdWCnBEqYBe8zhhbEJE8jq10KyXuEdW7c06RRSX~0mUkIsfuBRSUiGHPmxmuBMtljHSQQYse6sMlpCC9LpQBtgc0teYw__&Key-Pair-Id=K2L8F4GPSG1IFC", source: hyper_util::client::legacy::Error(SendRequest, hyper::Error(IncompleteMessage)) }). Retrying...
    at /home/runner/work/xet-core/xet-core/cas_client/src/http_client.rs:233

  2025-09-22T10:27:25.060426Z  WARN  Retry attempt #0. Sleeping 601.670959ms before the next attempt
    at /root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/reqwest-retry-0.7.0/src/middleware.rs:171

  2025-09-22T10:27:25.060511Z  WARN  Reqwest(reqwest::Error { kind: Request, url: "https://transfer.xethub.hf.co/xorbs/default/ede5feb7c2c3c86a257381efd075e4ac0c4c4762420f03b3d0d242d586ee81ca?X-Xet-Signed-Range=bytes%3D15229-2222928&X-Xet-Session-Id=01K5RFCJ5WPCN32T2KJ8P69QHX&Expires=1758540414&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly90cmFuc2Zlci54ZXRodWIuaGYuY28veG9yYnMvZGVmYXVsdC9lZGU1ZmViN2MyYzNjODZhMjU3MzgxZWZkMDc1ZTRhYzBjNGM0NzYyNDIwZjAzYjNkMGQyNDJkNTg2ZWU4MWNhP1gtWGV0LVNpZ25lZC1SYW5nZT1ieXRlcyUzRDE1MjI5LTIyMjI5MjgmWC1YZXQtU2Vzc2lvbi1JZD0wMUs1UkZDSjVXUENOMzJUMktKOFA2OVFIWCIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc1ODU0MDQxNH19fV19&Signature=QzPedlD8nEQCLik3hPbYGhPlIvC9znMrLnEblexHIIqhPXYu9pVK48vKFkyrGWoEE8fWqJtmx6rsbxzouqQ2vE5IqoORp66Vf2g8dACExCBymnTLOvqWLj9n4H-OyahEwcAANbBLDZq5gvxAuU7cZGFnwlrW4KRPw5byuJlnzePy7Z~UFiPft~QbY2bkXOVB~htBw5po18vTFAGh3iaLm189bzGdtIluKJOGD2xYfIPwrJNfC~hThAVPTWlJovWo4GGO-fLcl5QWu0jibIXFY4VVk~UNW0D2AOKvNmyD4kSMaxBL5rnPLGJFJSHWCisAp-~cFytejw5QSKkRXYOHZw__&Key-Pair-Id=K2L8F4GPSG1IFC", source: hyper_util::client::legacy::Error(SendRequest, hyper::Error(IncompleteMessage)) }). Retrying...
    at /home/runner/work/xet-core/xet-core/cas_client/src/http_client.rs:233

  2025-09-22T10:27:25.060541Z  WARN  Retry attempt #0. Sleeping 2.899259593s before the next attempt
    at /root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/reqwest-retry-0.7.0/src/middleware.rs:171

  2025-09-22T10:27:25.061163Z  WARN  Reqwest(reqwest::Error { kind: Request, url: "https://transfer.xethub.hf.co/xorbs/default/ede5feb7c2c3c86a257381efd075e4ac0c4c4762420f03b3d0d242d586ee81ca?X-Xet-Signed-Range=bytes%3D40290395-42480652&X-Xet-Session-Id=01K5RFCJ5WPCN32T2KJ8P69QHX&Expires=1758540414&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly90cmFuc2Zlci54ZXRodWIuaGYuY28veG9yYnMvZGVmYXVsdC9lZGU1ZmViN2MyYzNjODZhMjU3MzgxZWZkMDc1ZTRhYzBjNGM0NzYyNDIwZjAzYjNkMGQyNDJkNTg2ZWU4MWNhP1gtWGV0LVNpZ25lZC1SYW5nZT1ieXRlcyUzRDQwMjkwMzk1LTQyNDgwNjUyJlgtWGV0LVNlc3Npb24tSWQ9MDFLNVJGQ0o1V1BDTjMyVDJLSjhQNjlRSFgiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE3NTg1NDA0MTR9fX1dfQ__&Signature=On64dTEzTYZ3yoZF81risv91DCisXqI2-YA-Rlx4UiCiHYivOA8yraZmAk0c79tKhWZAqrPiTo1-bz1Q3PVoMRxuhFz~fGnvRnPxWNoOIUfi04B3i-ebOWZNtJJoUfxbxKsX81srHse21Cx5lINWwWVM4xG9PWm823UfmHQsoOdVvKr3Q3iLcbreyNR15R4MWxuWEHjAzyQ2VR289brC~96z8apd5iAFqzn58xaIHQHtxMbF4mykAzmyq3bNZOMSRFKa89CwxJGObGFW~0vZvtM-Atjj5GB6MpKR6SMQI4-30uWrkrzAQ9e4Fr3OJvbHu4fFNV~NaWtkU2nns~CvjA__&Key-Pair-Id=K2L8F4GPSG1IFC", source: hyper_util::client::legacy::Error(SendRequest, hyper::Error(IncompleteMessage)) }). Retrying...
    at /home/runner/work/xet-core/xet-core/cas_client/src/http_client.rs:233

  2025-09-22T10:27:25.061196Z  WARN  Retry attempt #0. Sleeping 57.820555ms before the next attempt
    at /root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/reqwest-retry-0.7.0/src/middleware.rs:171

  2025-09-22T10:27:25.065402Z  WARN  Reqwest(reqwest::Error { kind: Request, url: "https://transfer.xethub.hf.co/xorbs/default/ede5feb7c2c3c86a257381efd075e4ac0c4c4762420f03b3d0d242d586ee81ca?X-Xet-Signed-Range=bytes%3D15683138-17840645&X-Xet-Session-Id=01K5RFCJ5WPCN32T2KJ8P69QHX&Expires=1758540414&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly90cmFuc2Zlci54ZXRodWIuaGYuY28veG9yYnMvZGVmYXVsdC9lZGU1ZmViN2MyYzNjODZhMjU3MzgxZWZkMDc1ZTRhYzBjNGM0NzYyNDIwZjAzYjNkMGQyNDJkNTg2ZWU4MWNhP1gtWGV0LVNpZ25lZC1SYW5nZT1ieXRlcyUzRDE1NjgzMTM4LTE3ODQwNjQ1JlgtWGV0LVNlc3Npb24tSWQ9MDFLNVJGQ0o1V1BDTjMyVDJLSjhQNjlRSFgiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE3NTg1NDA0MTR9fX1dfQ__&Signature=GMUt4uOSlboMCsZtzi0w9H-DPIJE-QGziSEL14k7-7CaB3lwrD-IxF4adJI0SLhveW055R5j0hWQFAKK1ChJlnouLqBKMJ1k62ipD0WUgcIA8mcj~SMrJ1Q72reIOG9RS3zpnc59bx4h8RWZ3WnHnzpfG7wNBhDDiw3QopBR5EfsCaUmbPemA2tC0TTESUwUVzJJl0-VI3EeN63ZcRHAuTeJoiP9WMHGhdHAWzGqpa3qIYnN6lRO37qKRSQDbsyRx02ZyhnWpZOKl4l3UcrkYxUnpcRG4wHHZ-JqW~crMcZPhUaHwdPvvxVyIMyak78JkuOrf1ixiI~6lZQ5BR5Ehw__&Key-Pair-Id=K2L8F4GPSG1IFC", source: hyper_util::client::legacy::Error(SendRequest, hyper::Error(IncompleteMessage)) }). Retrying...
    at /home/runner/work/xet-core/xet-core/cas_client/src/http_client.rs:233

  2025-09-22T10:27:25.065431Z  WARN  Retry attempt #0. Sleeping 1.944860595s before the next attempt
    at /root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/reqwest-retry-0.7.0/src/middleware.rs:171

  2025-09-22T10:27:56.458594Z  WARN  Reqwest(reqwest::Error { kind: Request, url: "https://transfer.xethub.hf.co/xorbs/default/49145aa3ad9c46865a915641d235550644c6e520045d1b50851678ec241589df?X-Xet-Signed-Range=bytes%3D72361-1480152&X-Xet-Session-Id=01K5RFCJ5WPCN32T2KJ8P69QHX&Expires=1758540414&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly90cmFuc2Zlci54ZXRodWIuaGYuY28veG9yYnMvZGVmYXVsdC80OTE0NWFhM2FkOWM0Njg2NWE5MTU2NDFkMjM1NTUwNjQ0YzZlNTIwMDQ1ZDFiNTA4NTE2NzhlYzI0MTU4OWRmP1gtWGV0LVNpZ25lZC1SYW5nZT1ieXRlcyUzRDcyMzYxLTE0ODAxNTImWC1YZXQtU2Vzc2lvbi1JZD0wMUs1UkZDSjVXUENOMzJUMktKOFA2OVFIWCIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc1ODU0MDQxNH19fV19&Signature=py5gV0PVqk6H-O-mmkwtPvXHF3i0l5qDZDt7O87aqI8LmNoOkYsG9Oj91Dy19k6pnEYj0HM6PG7K8Dmd2tSRaXPoWHMnJeVY0PUeZhrmlvtuHCaKVXpha02OwzQRIgrgYDLki3nsHUA8ehRo6ElVrlAL7jeZCAJ3KxqUjOTFcX6TsCHBGaTN-77hxlJGkxg~xRKdLrgzhi4KgEgwv9ZLY0FSOGA9k1xG-itNZbrnX1xsq7YkmSJeAKtgjozdWCnBEqYBe8zhhbEJE8jq10KyXuEdW7c06RRSX~0mUkIsfuBRSUiGHPmxmuBMtljHSQQYse6sMlpCC9LpQBtgc0teYw__&Key-Pair-Id=K2L8F4GPSG1IFC", source: hyper_util::client::legacy::Error(SendRequest, hyper::Error(IncompleteMessage)) }). Retrying...
    at /home/runner/work/xet-core/xet-core/cas_client/src/http_client.rs:233

  2025-09-22T10:27:56.458662Z  WARN  Retry attempt #1. Sleeping 468.902818ms before the next attempt
    at /root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/reqwest-retry-0.7.0/src/middleware.rs:171

  2025-09-22T10:28:00.102325Z  WARN  Reqwest(reqwest::Error { kind: Request, url: "https://transfer.xethub.hf.co/xorbs/default/ab7f5f7c1eed0ce317ed7dec59e69e1894a72b8440dd20395037f1908e4e8866?X-Xet-Signed-Range=bytes%3D0-61136276&X-Xet-Session-Id=01K5RFCJ5WPCN32T2KJ8P69QHX&Expires=1758540414&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly90cmFuc2Zlci54ZXRodWIuaGYuY28veG9yYnMvZGVmYXVsdC9hYjdmNWY3YzFlZWQwY2UzMTdlZDdkZWM1OWU2OWUxODk0YTcyYjg0NDBkZDIwMzk1MDM3ZjE5MDhlNGU4ODY2P1gtWGV0LVNpZ25lZC1SYW5nZT1ieXRlcyUzRDAtNjExMzYyNzYmWC1YZXQtU2Vzc2lvbi1JZD0wMUs1UkZDSjVXUENOMzJUMktKOFA2OVFIWCIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc1ODU0MDQxNH19fV19&Signature=dnofTO9vjkWJDTWGcbkY~-r11SMd-JyDgbVvkvx7mW8LBkboGmuuJQPyzYPjHE-Vbqo0ww1422MlicgD-BJTVN99tDJ-yhbnapKTSDg~hi4ln3jgMu-OSaeyFSXPhkSDF0lCGUEhQT06T7hokk4nniY24lSFK1TcmIV9soZWBuynzKkr4n6bl5gJz-AaFXd~gBD98svXlcxaZpQdychTmzl04MiEDhvKEATVo80n-6xoga4-hIHZLKQdIR3e3K7we972lBT4qTQn-Dg-cmF52MWUJ2LvR7wN7GS7XLCricBBpitudQHsPnC4lNAUbfpMEK~Kj-XprvuKtTltB0M0dg__&Key-Pair-Id=K2L8F4GPSG1IFC", source: hyper_util::client::legacy::Error(SendRequest, hyper::Error(Io, Os { code: 110, kind: TimedOut, message: "Connection timed out" })) }). Retrying...
    at /home/runner/work/xet-core/xet-core/cas_client/src/http_client.rs:233

  2025-09-22T10:28:00.102464Z  WARN  Retry attempt #1. Sleeping 2.489724028s before the next attempt
    at /root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/reqwest-retry-0.7.0/src/middleware.rs:171

Cancellation requested; stopping current tasks.

KeyboardInterrupt:

In [ ]:
# =====================================
# 8. Save Model
# =====================================
model.save_pretrained("distilbert-tf-statement-pair")
tokenizer.save_pretrained("distilbert-tf-statement-pair")